name: oulad_project
version: "1.0.0"
config-version: 2

profile: oulad_project
require-dbt-version: [">=1.10.0", "<2.0.0"]

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  oulad_project:
    dimensions:
      +materialized: table
    facts:
      +materialized: table
    reporting:
      +materialized: view
